import React from 'react';
import "./globals.css";
import Header from "../components/Header";
import AppProvider from "@/hooks";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <Header />

        <main>
          <AppProvider>
            {children}
          </AppProvider>
        </main>
        
      </body>
    </html>
  );
}
